### ISSUE TITLE
PackagesNotFoundError while building environment

### ISSUE THREAD

**Issue by Gracesta** [umair-nasir14/Word2World#2]
Hello, thanks for your interesting work. I tried to run Word2World but stuck in building conda environment.

When I run `conda env create -f environment.yml` , the errors below were reported:

> Channels:
>  - defaults
>  - nodefaults
>  - conda-forge
> Platform: linux-64
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - zlib==1.2.13=h8cc25b3_0
>   - xz==5.4.2=h8cc25b3_0
>   - wheel==0.41.2=py310haa95532_0
>   - vs2015_runtime==14.27.29016=h5e58377_2
>   - vc==14.2=h21ff451_1
>   - tk==8.6.12=h2bbff1b_0
>   - sqlite==3.41.2=h2bbff1b_0
>   - setuptools==68.0.0=py310haa95532_0
>   - pip==23.2.1=py310haa95532_0
>   - openssl==3.0.11=h2bbff1b_2
>   - libffi==3.4.4=hd77b12b_0
>   - ca-certificates==2023.08.22=haa95532_0
>   - bzip2==1.0.8=he774522_0
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/linux-64
>   - https://repo.anaconda.com/pkgs/r/linux-64
>   - https://conda.anaconda.org/nodefaults/linux-64
>   - https://conda.anaconda.org/conda-forge/linux-64
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

Specified version might be tricky sometimes, so I tried to remove the last version code.
Even so, still two packages were not found:
>   - vs2015_runtime=14.27.29016*
>   - vc=14.2*

My environment is **Linux**, conda version is **24.3.0**.

I'm really interested at your work and wonder if I can get help here to run this project.

Thanks!

**Comment by umair-nasir14** [comment]
Thank you for notifying the issue and your interest in the project!

Unfortunately, the environment is not tested for Linux, but I am looking into the issue and I hope to get it sorted asap!

Meanwhile, it could be an option to run with a custom environment, till I get the fix. Major requirements are the following:

- transformers==4.38.2
- torch==2.2.1+cu118
- seaborn
- scipy==1.12.0
- scikit-image==0.22.0
- python==3.10.13
- pillow
- numpy
- matplotlib
- openai==0.28.1

Thanks again!

**Comment by Gracesta** [comment]
Thanks for you quick reply!

Can I ask what the supported platform is, is it Windows?

And thanks for the custom environment building guide!

I'll have a try!

**Comment by umair-nasir14** [comment]
It's my pleasure. I would love to help you run the project.

Yes, currently it is Windows which also supports your PR as the paths will be an issue in Linux.

**Comment by umair-nasir14** [comment]
Hi @Gracesta! I have created a branch `environment-fix` for this issue. I have added `environment-fix.yml`, which again works on windows but I have not checked for Linux.

It would be a great addition to the project to make it Linux supported. I would love to help but I am currently busy with a NeurIPS project and would only be able to help in June. You PR can be extended to support Linux fully because a lot of paths might need changes actually.

**Comment by Gracesta** [comment]
Glad to hear from you again, @umair-nasir14 !
It's so kind of you to provide me the environment for Linux. After applying the environment settings you suggested to me before, I successfully ran the code anyway, but many exceptions reported.

And maybe those happened exceptions would hurt the quality of the generated stage, I would like to try to figure it out. Thanks for your information and the ` environment-fix.yml`, I'd like to have a try with ` environment-fix.yml`. your work is really interesting and I wanna have a exploration.

Good luck with your NeurIPS project!

**Comment by umair-nasir14** [comment]
Thank you, @Gracesta!

It is good to hear that the project worked! I hope you enjoy it.

Maybe you can create the environment for linux whenever you can, would be nice!

Let me know if I can help with the warnings. The error-catching should not hurt the generation part, but let me know what you find!

Thanks again!
